<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Login2 extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Member_model');
        $this->load->model('Admin_model');
    }

    public function index()
    {
		if($this->session->userdata('logined') && $this->session->userdata('logined') == true)
		{
			redirect('member');
		}
		
		if(!$this->input->post())
		{
			$this->load->view('login2');
		}
		else
		{
			$pilihan = $this->input->post('pilihan');
			if($pilihan == 2){
				$cek_login=$this->Member_model->cek_login(
				$this->input->post('username'),
				$this->input->post('password')
				);
				$this->session->set_userdata('status', 'member');
			}
			else{
				$cek_login=$this->Admin_model->cek_login(
				$this->input->post('username'),
				$this->input->post('password')
				);
				$this->session->set_userdata('status', 'admin');
			}
			if(!empty($cek_login))
			{
				$this->session->set_userdata('logined', true);
				$this->session->set_userdata('username', $cek_login->username);
				if($this->session->userdata('status') == 'member') {
					redirect('home');
				}
				else{
					redirect('member');
				}
			}
			else 
			{
				$this->session->set_flashdata('gagal','<div class="alert alert-danger"><strong>Gagal Login</strong> Username dan Password Anda Salah.
					</div>');
				redirect("login");
			}
		}
        
    } 
	
	public function logout()
    {
		$this->session->unset_userdata('logined');
		redirect("login");
    } 
}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */