<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class registrasi extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Member_model');
    }

    public function index()
    {
		$data = array(
			'nama_member' => set_value('nama_member'),
			'username' => set_value('username'),
			'password' => set_value('password'),
			'kelas_member' => set_value('kelas_member'),
			'jurusan_member' => set_value('jurusan_member'),
			'prodi_member' => set_value('prodi_member'),
			'id_member' => set_value('id_member'),
			'button' => 'Tambah',
			'action' => site_url('registrasi/tambah_aksi')
			);
		$this->load->view('registrasi', $data);
	}

	function tambah_aksi()
	{
		$data = array(
			'nama_member' => $this->input->post('nama_member'),
			'username' => $this->input->post('username'),
			'password' => $this->input->post('password'),
			'kelas_member' => $this->input->post('kelas_member'),
			'jurusan_member' => $this->input->post('jurusan_member'),
			'prodi_member' => $this->input->post('prodi_member'),
			);
		$this->Member_model->tambah_data($data);
		redirect(site_url('login'));
	}
    
}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */